apiVersion: v1
kind: Secret
metadata:
  name: schedule-servicedb-login
type: Opaque
data:
  databaseName: c2NoZWR1bGVfZGI=
  rootPassword: c2VjcmV0
  username: c2NoZWR1bGVfZGJfdXNlcg==
  password: c2NoZWR1bGVfZGJfdXNlcl9wYXNz