version: '3'
services:
  questionnaireServiceDB:
    image: mysql:5.7
    container_name: questionnaireServiceDB
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: questionnaire_db
      MYSQL_USER: questionnaire_db_user
      MYSQL_PASSWORD: questionnaire_db_user_pass
    ports:
      - "6035:3306"
    volumes:
      - questionnaireServiceDataVolume:/home/soa/project/data/questionnaireServiceDB
#Un-commit this to run adminer to manager mysql
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8082:8080
volumes:
  questionnaireServiceDataVolume:


networks:
  default:
    external:
      name: ratefy-network