version: '3'
services:
  questionnaireServiceDB:
    image: mysql:5.7
    container_name: questionnaireServiceDB
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: questionnaire_db
      MYSQL_USER: questionnaire_db_user
      MYSQL_PASSWORD: questionnaire_db_user_pass
    ports:
      - "6033:3306"
    volumes:
      - questionnaireServiceDataVolume:/home/soa/project/data/feebackServiceDB
volumes:
  questionnaireServiceDataVolume: