# ... Deployment YAML definition
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-app
      tier: backend
  template:
    metadata:
      labels:
        app: student-app
        tier: backend
    spec:
      containers:
        - name: student-app
          image: peshmerge/student-service:1.0.0
          ports:
            - containerPort: 9096
              name: service-port
          env:
            - name: STUDENT_SERVICE_DB
              value: student-service-db:3306/student_db?autoReconnect=true
            - name: USER_SERVICE_DB_USER
              valueFrom:
                secretKeyRef:
                  name: student-servicedb-login
                  key: username
            - name: USER_SERVICE_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: student-servicedb-login
                  key: password
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              port: service-port
              path: /actuator/health
            initialDelaySeconds: 20
            timeoutSeconds: 5
---
# ... Service YAML definition
apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student-app
    tier: backend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 9096
  type: ClusterIP