version: '3'
services:
  feedbackServiceDB:
    image: mysql:5.7
    container_name: feedbackServiceDB
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: feedback_db
      MYSQL_USER: feedback_db_user
      MYSQL_PASSWORD: feedback_db_user_pass
    ports:
      - "6034:3306"
    volumes:
      - feedbackServiceDataVolume:/home/soa/project/data/feedbackServiceDB
#Un-commit this to run adminer to manager mysql
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8081:8080
volumes:
  feedbackServiceDataVolume:


