# Check this url https://kubernetes.io/docs/tasks/run-application/run-single-instance-stateful-application/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: user-service-mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-db
spec:
  selector:
    app: user-mysql-app
  ports:
    - port: 3306
      targetPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-mysql-deployment
spec:
  selector:
    matchLabels:
      app: user-mysql-app
      tier: backend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: user-mysql-app
        tier: backend
    spec:
      containers:
        - name: user-mysql-app
          image: mysql:5.7
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: user-servicedb-login
                  key: databaseName
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: user-servicedb-login
                  key: username
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-servicedb-login
                  key: password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: user-servicedb-login
                  key: rootPassword
          volumeMounts:
            - name: user-data-volume
              mountPath: /var/lib/mysql
      volumes:
        - name: user-data-volume
          persistentVolumeClaim:
            claimName: user-service-mysql-pvc