apiVersion: v1
kind: Service
metadata:
  name: questionnaire-service-db
spec:
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 6035

---
apiVersion: v1
kind: Endpoints
metadata:
  name: questionnaire-service-db
subsets:
  - addresses:
      - ip: 10.0.2.2
    ports:
      - port: 6035