apiVersion: v1
kind: Secret
metadata:
  name: questionnaire-servicedb-login
type: Opaque
data:
  databaseName: cXVlc3Rpb25uYWlyZV9kYg==
  rootPassword: c2VjcmV0
  username: cXVlc3Rpb25uYWlyZV9kYl91c2Vy
  password: cXVlc3Rpb25uYWlyZV9kYl91c2VyX3Bhc3M=