version: "3.9"
services:
  studentServiceDB:
    image: mysql:5.7
    container_name: studentServiceDB
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: student_db
      MYSQL_USER: student_db_user
      MYSQL_PASSWORD: student_db_user_pass
    ports:
      - "6039:3306"
    volumes:
      - studentkServiceDataVolume:/home/soa/project/data/studentServiceDB
#Un-commit this to run adminer to manager mysql
  adminer:
    image: adminer
    restart: on-failure
    ports:
      - 8086:8080
volumes:
  studentkServiceDataVolume:

networks:
  default:
    external:
      name: ratefy-network